---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: secret-copier-acc
imagePullSecrets:
  - name: registry-creds

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: secret-copier
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-copier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-copier
subjects:
  - kind: ServiceAccount
    name: secret-copier-acc
    namespace: tanzu-developer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: secret-copier-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmware-system-tmc-psp-privileged
subjects:
  - kind: ServiceAccount
    name: secret-copier-acc
    namespace: tanzu-developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  labels:
    app: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
    spec:
      containers:
      - name: shell-operator
        image: registry.test.eduk8s.io/image-puller-secret-operator:latest
        imagePullPolicy: Always
      serviceAccountName: secret-copier-acc
