---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pull-secret-copier
imagePullSecrets:
  - name: registry-creds

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: pull-secret-copier
rules:
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["*"]
- apiGroups: [""]
  resources: ["serviceaccounts"]
  verbs: ["*"]

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-copier
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: secret-copier
subjects:
  - kind: ServiceAccount
    name: pull-secret-copier
    namespace: tanzu-developer
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: pull-secret-copier-privileged
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vmware-system-tmc-psp-privileged
subjects:
  - kind: ServiceAccount
    name: pull-secret-copier
    namespace: tanzu-developer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pull-secret-copier
  labels:
    app: pull-secret-copier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pull-secret-copier
  template:
    metadata:
      labels:
        app: pull-secret-copier
    spec:
      containers:
      - name: pull-secret-copier
        image: registry.test.eduk8s.io/image-puller-secret-operator:latest
        env:
        - name: MAIN_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        imagePullPolicy: IfNotPresent
      serviceAccountName: pull-secret-copier
