#!/usr/bin/env bash

source /hooks/common/functions.sh

hook::config() {
  cat <<EOF
{
  "configVersion": "v1",
  "kubernetes": [
    {
      "apiVersion": "v1",
      "kind": "secret",
      "executeHookOnEvent": [
        "Deleted"
      ],
      "labelSelector": {
        "matchLabels": {
            "pull-secret": "yes"
        }
      },
      "namespace": {
        "nameSelector": {
          "matchNames": [
            "${MAIN_NAMESPACE}"
          ]
        }
      }
    }
  ]
}
EOF
}

hook::trigger() {
  # ignore Synchronization for simplicity
  type=$(jq -r '.[0].type' $BINDING_CONTEXT_PATH)
  if [[ $type == "Synchronization" ]] ; then
    echo Got Synchronization event
    exit 0
  fi

  for secret in $(jq -r '.[] | .object.metadata.name' $BINDING_CONTEXT_PATH)
    do
      for namespace in $(kubectl get namespace -o json |
                          jq -r ".items[] |
                            select((.metadata.name == \"${MAIN_NAMESPACE}\" | not) and .status.phase == \"Active\") | .metadata.name")
      do
        for serviceaccount in $(kubectl -n ${namespace} get serviceaccount -o jsonpath="{.items[*].metadata.name}");
        do
          # Remove the secret as imagePullSecrets/secret from every serviceaccount in the namespace
          kubectl -n ${namespace} get serviceaccount ${serviceaccount} -o json \
            | jq -r ".imagePullSecrets |= (. - [{\"name\": \"${secret}\"}]) | .secrets |= (. - [{\"name\": \"${secret}\"}])" \
            | kubectl::apply
        done
        kubectl -n $namespace delete secret $secret >/dev/null 2>/dev/null | true
      done
    done
}

common::run_hook "$@"
